### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by yumoto34492** [yumoto34492/protospace-34492#1]
#URL
https://protospace-34492.herokuapp.com/

**Comment by rumaruma0408** [comment]
yumoto34492さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by yumoto34492** [comment]
確認ありがとうございました！
